# Generated by Django 5.0.6 on 2025-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO'), ('AJUSTE+', 'AJUSTE+'), ('AJUSTE-', 'AJUSTE-')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('documento', models.CharField(blank=True, max_length=120, null=True)),
                ('externo_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPorDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_minima', models.IntegerField(default=0)),
            ],
        ),
    ]
