# Generated by Django 5.0.6 on 2025-08-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('inventario', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='user.taller'),
        ),
        migrations.AddField(
            model_name='stockpordeposito',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.deposito'),
        ),
        migrations.AddField(
            model_name='stockpordeposito',
            name='repuesto_taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalogo.repuestotaller'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='stock_por_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.stockpordeposito'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='id_stock_por_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.stockpordeposito'),
        ),
        migrations.AlterUniqueTogether(
            name='deposito',
            unique_together={('taller', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='stockpordeposito',
            unique_together={('repuesto_taller', 'deposito')},
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('externo_id', None), _negated=True), fields=('stock_por_deposito', 'externo_id'), name='uq_mov_extid_por_stock'),
        ),
    ]
