# Generated by Django 5.0.6 on 2025-09-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpordeposito',
            name='cantidad_minima',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO'), ('AJUSTE+', 'AJUSTE+'), ('AJUSTE-', 'AJUSTE-'), ('INICIAL+', 'INICIAL+'), ('INICIAL-', 'INICIAL-')], max_length=10),
        ),
    ]
