# Generated by Django 5.0.6 on 2025-10-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_repuestotaller_frecuencia'),
        ('inventario', '0003_remove_stockpordeposito_cantidad_minima_and_more'),
        ('user', '0004_direccion_pais_user_rol_en_grupo_alter_user_grupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='ObjetivoKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_rotacion_objetivo', models.DecimalField(decimal_places=2, default=1.5, help_text='Objetivo de tasa de rotación trimestral', max_digits=5)),
                ('dias_en_mano_objetivo', models.IntegerField(default=60, help_text='Objetivo de días en mano')),
                ('dead_stock_objetivo', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje máximo aceptable de dead stock', max_digits=5)),
                ('dias_dead_stock', models.IntegerField(default=730, help_text='Días sin movimiento para considerar dead stock (2 años)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_kpi', to='user.grupo')),
                ('taller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_kpi', to='user.taller')),
            ],
            options={
                'verbose_name': 'Objetivo KPI',
                'verbose_name_plural': 'Objetivos KPI',
            },
        ),

    ]
