# Generated by Django 5.0.6 on 2025-11-06 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_repuestotaller_frecuencia'),
        ('inventario', '0004_alerta_objetivokpi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CRITICO', 'Crítico'), ('MEDIO', 'Medio'), ('ADVERTENCIA', 'Advertencia'), ('INFORMATIVO', 'Informativo')], max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('VISTA', 'Vista'), ('DESCARTADA', 'Descartada'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('datos_snapshot', models.JSONField(blank=True, help_text='Stock, forecast, etc. al momento de la creación', null=True)),
                ('descartada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repuesto_taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='catalogo.repuestotaller')),
            ],
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['NUEVA', 'VISTA'])), fields=('repuesto_taller', 'codigo'), name='alerta_activa_unica_por_repuesto_y_codigo'),
        ),
        migrations.AlterUniqueTogether(
            name='alerta',
            unique_together={('repuesto_taller', 'codigo', 'estado')},
        ),
    ]
