from dataclasses import dataclass
class NotFoundError(Exception): ...
class DuplicateError(Exception): ...
class StockInsufficientError(Exception): ...
@dataclass(frozen=True)
class RepoResult: obj: object; created: bool=False
