# Generated by Django 5.0.6 on 2025-08-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pieza', models.CharField(db_index=True, max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloRepuesto',
            fields=[
                ('id_modelo_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('id_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.modelo')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoTaller',
            fields=[
                ('id_repuesto_taller', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('original', models.BooleanField(default=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.repuesto')),
            ],
        ),
    ]
