# Generated by Django 5.0.6 on 2025-08-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestotaller',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.taller'),
        ),
        migrations.AlterUniqueTogether(
            name='repuestotaller',
            unique_together={('repuesto', 'taller')},
        ),
    ]
