# Generated by Django 5.0.6 on 2025-09-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestotaller',
            name='pred_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repuestotaller',
            name='pred_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repuestotaller',
            name='pred_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repuestotaller',
            name='pred_4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
