# Generated by Django 5.0.6 on 2025-10-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_taller_localizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='pais',
            field=models.CharField(default='Argentina', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rol_en_grupo',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador del Grupo'), ('member', 'Miembro'), ('viewer', 'Observador')], default='member', help_text='Solo aplica si pertenece a un grupo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='user.grupo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='user.taller'),
        ),
    ]
