# Generated by Django 5.0.6 on 2025-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_direccion_pais_user_rol_en_grupo_alter_user_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_en_taller',
            field=models.CharField(blank=True, choices=[('owner', 'Dueño del Taller'), ('member', 'Miembro')], help_text='Solo aplica si pertenece a un taller', max_length=20, null=True),
        ),
    ]
