# Generated by Django 5.0.6 on 2025-09-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_externo', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroentrenamiento_frecuencia_alta',
            old_name='numero_parte',
            new_name='numero_pieza',
        ),
        migrations.RenameField(
            model_name='registroentrenamiento_intermitente',
            old_name='numero_parte',
            new_name='numero_pieza',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_delta',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_ema_12',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_ema_3',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_ema_6',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_lag_1',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_lag_2',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_lag_3',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prendas_lag_6',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='coef_var_52',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='media_ultimas_52',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_delta',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_ema_12',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_ema_3',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_ema_6',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_lag_1',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_lag_2',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_lag_3',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='prendas_lag_6',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='std_pasada_52_semanas',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_27',
        ),
        migrations.RemoveField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_28',
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Delta)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (EMA 12)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (EMA 3)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (EMA 6)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 1)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 2)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 3)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='prenda_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 6)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Delta)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (EMA 12)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (EMA 3)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (EMA 6)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 1)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 2)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 3)'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='prenda_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Prendas (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='cantidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='coef_var_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 12 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='coef_var_26',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 26 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='coef_var_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 4 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='coef_var_52',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 52 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='coef_var_8',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 8 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='dias_hasta_feriado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días Hasta Feriado'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='es_semana_feriado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Es Semana Feriada'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='hubo_venta',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hubo Venta'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='inflacion_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ipsa_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='media_ultimas_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 12 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='media_ultimas_26',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 26 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='media_ultimas_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 4 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='media_ultimas_52',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 52 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='media_ultimas_8',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 8 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_11',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_7',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='mes_9',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='patentamientos_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='patentamientos_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='patentamientos_ema_24',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (EMA 24)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='patentamientos_lag_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Lag 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='patentamientos_lag_24',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Lag 24)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='patentamientos_lag_36',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Lag 36)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_11',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_13',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_14',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_15',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_16',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_17',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_18',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_19',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_20',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_21',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_22',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_23',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_24',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_25',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_26',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_27',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_28',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_29',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_30',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_31',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_32',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_33',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_34',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_35',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_36',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_37',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_38',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_39',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_40',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_41',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_42',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_43',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_44',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_45',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_46',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_47',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_48',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_49',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_50',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_51',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_52',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_7',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='semana_9',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='std_pasada_12_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 12 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='std_pasada_26_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 26 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='std_pasada_4_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 4 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='std_pasada_52_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 52 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='std_pasada_8_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 8 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tasa_de_interes_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='tipo_de_cambio_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='trimestre_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='trimestre_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='trimestre_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='trimestre_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_10',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-10)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_11',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-11)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_13',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-13)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_14',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-14)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_15',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-15)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_16',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-16)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_17',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-17)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_18',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-18)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_19',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-19)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_20',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-20)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_21',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-21)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_22',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-22)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_23',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-23)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_24',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-24)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_25',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-25)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_26',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-26)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_27',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-27)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_28',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-28)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_29',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-29)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_30',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-30)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_31',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-31)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_32',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-32)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_33',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-33)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_34',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-34)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_35',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-35)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_36',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-36)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_37',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-37)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_38',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-38)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_39',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-39)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-4)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_40',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-40)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_41',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-41)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_42',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-42)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_43',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-43)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_44',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-44)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_45',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-45)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_46',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-46)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_47',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-47)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_48',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-48)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_49',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-49)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-5)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_50',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-50)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_51',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-51)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_52',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-52)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_7',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-7)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_8',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-8)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='ventas_t_9',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-9)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='cantidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='coef_var_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 12 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='coef_var_26',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 26 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='coef_var_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 4 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='coef_var_8',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación 8 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='dias_hasta_feriado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días Hasta Feriado'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='es_semana_feriado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Es Semana Feriada'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='hubo_venta',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hubo Venta'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='inflacion_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflación (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ipsa_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='IPSA (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='media_ultimas_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 12 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='media_ultimas_26',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 26 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='media_ultimas_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 4 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='media_ultimas_8',
            field=models.FloatField(blank=True, null=True, verbose_name='Media Últimas 8 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_11',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_7',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='mes_9',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='patentamientos_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='patentamientos_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='patentamientos_ema_24',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (EMA 24)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='patentamientos_lag_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Lag 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='patentamientos_lag_24',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Lag 24)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='patentamientos_lag_36',
            field=models.FloatField(blank=True, null=True, verbose_name='Patentamientos (Lag 36)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_11',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_13',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_14',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_15',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_16',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_17',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_18',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_19',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_20',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_21',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_22',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_23',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_24',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_25',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_26',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_27',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_28',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_29',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_30',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_31',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_32',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_33',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_34',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_35',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_36',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_37',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_38',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_39',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_40',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_41',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_42',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_43',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_44',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_45',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_46',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_47',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_48',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_49',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_50',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_51',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_52',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_7',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='semana_9',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='std_pasada_12_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 12 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='std_pasada_26_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 26 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='std_pasada_4_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 4 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='std_pasada_8_semanas',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar Últimas 8 Semanas'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tasa_de_interes_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Interés Préstamos (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_delta',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Delta)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_ema_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (EMA 12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_ema_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (EMA 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_ema_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (EMA 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_lag_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_lag_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_lag_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='tipo_de_cambio_lag_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tipo de Cambio (Lag 6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='trimestre_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='trimestre_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='trimestre_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='trimestre_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-1)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_10',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-10)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_11',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-11)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_12',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-12)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_13',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-13)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_14',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-14)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_15',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-15)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_16',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-16)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_17',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-17)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_18',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-18)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_19',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-19)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-2)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_20',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-20)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_21',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-21)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_22',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-22)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_23',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-23)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_24',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-24)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_25',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-25)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_26',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-26)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-3)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-4)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-5)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-6)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_7',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-7)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_8',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-8)'),
        ),
        migrations.AlterField(
            model_name='registroentrenamiento_intermitente',
            name='ventas_t_9',
            field=models.FloatField(blank=True, null=True, verbose_name='Ventas (t-9)'),
        ),
    ]
